### ISSUE TITLE
Adding files / images does not work

### ISSUE THREAD

**Issue by macbih** [hbrennhaeuser/homeassistant_integration_ntfy#12]
First of all thank you for your awesome integration!

My setup basically does work. The integration is able to send messages including e.g. setting priority. But I am unfortunately not able to attach images to it!

While this notification with Pushover works flawlessly (I would like to replace it with ntfy)

```
      - action: notify.pushover
        data:
          title: Entrance
          message: Person detected!
          data:
            attachment: "/media/kameras/doorbell/person.jpg"
```

this one (which is almost identical) fails and just sends title and message:

```
      - action: notify.ntfy
        data:
          title: Entrance
          message: Person detected!
          data:
            attach_file: "/media/kameras/doorbell/person.jpg"
            attachment_filename: 'person.jpg'
```

According to the docs the syntax should be okay but it fails. I tried to add `/local` to the image path but saw no difference. 

I am also able to send notifications including images or files from the [ntfy.sh account page](https://ntfy.sh/account) onto my topic.

My account type is Free. This is my setup (using https://ntfy.sh):

```
- name: ntfy
  platform: ntfy
  url: !secret ntfy_url
  authentication: 'token'
  token: !secret ntfy_token
  topic: mytopic
  #verify_ssl: True 
  allow_topic_override: True
  #attachment_maxsize: 2M
```

What am I doing wrong? I apologize if I have overlooked something trivial. Can you assist, please? Thank you!
