### ISSUE TITLE
Feature: Add support for actions

### ISSUE THREAD

**Issue by macbih** [hbrennhaeuser/homeassistant_integration_ntfy#13]
I heavily use [actionable notifications](https://companion.home-assistant.io/docs/notifications/actionable-notifications/) in the HA companion app, i.e. to acknowledge certain messages. Now I would like to create a comparable functionality with this integration. To achieve this, the integration may also support actions as described [here in the official documentation](https://docs.ntfy.sh/publish/#defining-actions).

I imagine something like this:

```
- action: notify.ntfy
  data:
    title: ntfy Actions
    message: Actions!
    data:
      actions:
        - action: "http"
          label: "Label 1"
          url: >-
            https://...
        - action: "view"
          label: "Label 2"
          ...
        - action: MAILBOX_ACKNOWLEDGE
          label: "Acknowledge"
```

You may like to take a look at https://community.home-assistant.io/t/ntfy-sh-with-actions/578603/ for additional inspirations.

**Comment by hbrennhaeuser** [comment]
I have added support for action buttons in release `v1.2.0-pre.1`, can you test if it works as expected for you?

The view-action is tested and should work fine.
The broadcast-action should work as well, but i haven't fully tested it yet, as I don't use any compatible automation app. 
The http action is not tested at all yet.

The documentation for the broadcast-action is not done yet, here's an example of how to use it:
```yaml
  data:
    actions:
      - action: broadcast
        label: "Take picture"
        intent: io.heckel.ntfy.USER_ACTION
        extras:
          - cmd: pic
          - camera: front
```
