### ISSUE TITLE
Action notify.ntfy_notification not found

### ISSUE THREAD

**Issue by Zaphod-dev** [hbrennhaeuser/homeassistant_integration_ntfy#14]
Hi,
I've added the integration via HACS, copied the Python files to config/custom_components/ntfy, added the YAML configuration, restarted HA, the integration is active (screenshot below) but I'm not seeing the new notify service , eg
![image](https://github.com/user-attachments/assets/1cd78dd9-4f5e-48dd-b0f1-35d4ef25ff3b)
("introuvable" means "not found")
Also I'm wondering why the Python files need to be under `config/custom_components/` since other HACS custom integrations appear to live under `custom_components/` ?
Any help appreciated :)
Many thanks !

My YAML file : 
```
notify:
    - name: ntfy_notification
      platform: ntfy
      authentication: 'False'
      #username: 'user' 
      #password: 'password' 
      #token: 'tk_odlbse211n74kf8N7h4qhqvj409qb'
      topic: '######################'
      url: 'https://ntfy.sh'
      verify_ssl: True
      allow_topic_override: False

```
![image](https://github.com/user-attachments/assets/94d3e54a-3b26-4faa-9c1d-6b358142f407)
