### ISSUE TITLE
send a priority message with Home Assistant

### ISSUE THREAD

**Issue by m0nn3** [hbrennhaeuser/homeassistant_integration_ntfy#17]
### Home Assistant Core Version

2025.2.1

### Home Assistant Installation Method

HA OS 14.2   Supervisor 2025.02.0

### Integration Version

1.0.2

### How was the integration installed?

HACS

### What happened?

Hello,

I have managed to connect Home Assistant to my NTFY server.
So far I can send normal messages without any problems.
Now that I have smoke detectors, I wanted to send them with priority 5.
But I always get this error message:

`extra keys not allowed @ data[‘priority’]. Got None`

Here is my YAML code:
```
action: notify.ntfy
metadata: {}
data:
  message: priority test
  priority: 5
```
Without priority: 5 it works without problems.

Can someone tell me what I am doing wrong?
Thank you very much for your help and the very good project!

### [Optional] Relevant log output

```shell

```

**Comment by m0nn3** [comment]
After I had sent the message, I played and tried a bit more.

Now it works with the following code:

```
action: notify.ntfy
metadata: {}
data:
  message: priority test
  data:
    priority: max
```

many thanks for that !!!


PS:

While I'm at it.
Is there a way that Home Assistant can also send messages in 2 different threads?
I would like to separate this a bit so that my wife doesn't get all the messages I might want :)

My configuration currently looks like this:

```
# Notifier
notify:
# NTFY
  - platform: ntfy
    name: "NTFY"
    authentication: 'token'
    token: 'tk_MyToken'
    topic: 'HomeAssistant'
    url: 'MyURL' 
    allow_topic_override: True
```
