### ISSUE TITLE
How can Home Assistant send messages in 2 different topics

### ISSUE THREAD

**Issue by m0nn3** [hbrennhaeuser/homeassistant_integration_ntfy#18]
### Home Assistant Core Version

2025.2.1

### Home Assistant Installation Method

HA OS 14.2 Supervisor 2025.02.0

### Integration Version

1.0.2

### How was the integration installed?

HACS

### What happened?

Is there a way that Home Assistant can also send messages in 2 different topics?
I would like to separate this a bit so that my wife doesn't get all the messages I might want :)

My configuration currently looks like this:

```
# Notifier
notify:
  - platform: ntfy
    name: "NTFY"
    authentication: 'token'
    token: 'tk_MyToken'
    topic: 'HomeAssistant'
    url: 'MyServer'  
    allow_topic_override: True 
## new Thread
  - platform: ntfy
    name: "Rauchmelder"
    authentication: 'token'
    token: 'tk_MyOtherToken'
    topic: 'Rauchmelder'
    url: 'MyServer' 
    allow_topic_override: True  
```

Unfortunately, I can only select Send a notification with NTFY for a new notification and not between NTFY and Rauchmelder.

It would be very nice if someone could help me how to send in multiple topics.

### [Optional] Relevant log output

```shell

```

**Comment by hbrennhaeuser** [comment]
Your configuration should work, I don't see anything wrong - Can you restart your Home Assistant and check if there is anything relevant in the system log that might give us a hint?

As a workaround you can remove the second entry "Rauchmelder" from your configuration.yaml and use topic-overrides in your automation like this:
```yaml
actions:
  - action: notify.NTFY
    data:
      title: Rauchmelder Alarm
      message: ...
      data:
        priority: high
        topic: Rauchmelder
```
