### ISSUE TITLE
Cannot send any messages with latest pre-version nor any of the pre-versions

### ISSUE THREAD

**Issue by michapixel** [hbrennhaeuser/homeassistant_integration_ntfy#25]
### Home Assistant Core Version

2025.5.2

### Home Assistant Installation Method

docker-container, via portainer (Unsupported Third Party Container)

### Integration Version

1.2.0-pre.3

### How was the integration installed?

HACS

### What happened?

I've added this repo to HACS and downloaded it via GUI, it installed fine (without errors). This was Version 1.0.2, sending messages to (self-hosted) ntfy works from the go.
But since i wanted to send a picture with my message i upgraded / redownloaded the latest version, 1.2.0-pre.3
Installation went smooth afaics.

i already had this in my configuartion.yaml:
```
notify:
  - name: ntfy_notification
    platform: ntfy
    authentication: 'token'
    token: 'tk_XXX'
    topic: 'homeassistant'
    url: 'https://XXX.XXX.XXX.XXX' 
    allow_topic_override: False
    attachment_maxsize: 10M
```

My (test) automation consist of only one action which i can run obn it's own via gui:
```
action: notify.ntfy_notification
data:
  title: 🤘
  message: Print is ready
  data:
    attach_file: /config/www/tmp/current_printmodel.jpg # file exists
    attachment_compress_image: 0
    attachment_filename: current_printmodel.jpg
    topic: print_ready
```

Now running this action results in an error:

`Action notify.ntfy_notification not found`

### [Optional] Relevant log output

```shell

```
