### ISSUE TITLE
Notify action no longer available

### ISSUE THREAD

**Issue by jdeluyck** [hbrennhaeuser/homeassistant_integration_ntfy#28]
### Home Assistant Core Version

2025.5.3

### Home Assistant Installation Method

HA OS

### Integration Version

1.2.0

### How was the integration installed?

HACS

### What happened?

notify.ntfy action is no longer available after upgrading to 1.2.0

In `configuration.yaml`
```yaml
notify: !include_dir_merge_list configuration/notify/
```

This is my configuration/notify/ntfy.yaml file
```yaml
- name: ntfy
  platform: ntfy
  authentication: "token"
  token: "<mytoken>"
  url: "https://<my host>"
  #verify_ssl: True
  allow_topic_override: True
```

This worked on prior versions, but not on 1.2.0. 

### [Optional] Relevant log output

```shell

```
